/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xin_manong_search_knn_index_hnsw_HNSWLoader */

#ifndef _Included_xin_manong_search_knn_index_hnsw_HNSWLoader
#define _Included_xin_manong_search_knn_index_hnsw_HNSWLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xin_manong_search_knn_index_hnsw_HNSWLoader
 * Method:    initLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_xin_manong_search_knn_index_hnsw_HNSWLoader_initLibrary
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
