/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xin_manong_search_knn_index_hnsw_HNSWIndex */

#ifndef _Included_xin_manong_search_knn_index_hnsw_HNSWIndex
#define _Included_xin_manong_search_knn_index_hnsw_HNSWIndex
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xin_manong_search_knn_index_hnsw_HNSWIndex
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_xin_manong_search_knn_index_hnsw_HNSWIndex_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     xin_manong_search_knn_index_hnsw_HNSWIndex
 * Method:    open
 * Signature: (Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_xin_manong_search_knn_index_hnsw_HNSWIndex_open
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     xin_manong_search_knn_index_hnsw_HNSWIndex
 * Method:    search
 * Signature: (J[FI)[Lxin/manong/search/knn/index/KNNResult;
 */
JNIEXPORT jobjectArray JNICALL Java_xin_manong_search_knn_index_hnsw_HNSWIndex_search
  (JNIEnv *, jobject, jlong, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
