/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xin_manong_search_knn_index_hnsw_HNSWIndexFactory */

#ifndef _Included_xin_manong_search_knn_index_hnsw_HNSWIndexFactory
#define _Included_xin_manong_search_knn_index_hnsw_HNSWIndexFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xin_manong_search_knn_index_hnsw_HNSWIndexFactory
 * Method:    build
 * Signature: ([I[[FLjava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_xin_manong_search_knn_index_hnsw_HNSWIndexFactory_build
  (JNIEnv *, jobject, jintArray, jobjectArray, jstring, jobjectArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
