/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class xin_manong_search_knn_index_faiss_FAISSIndexFactory */

#ifndef _Included_xin_manong_search_knn_index_faiss_FAISSIndexFactory
#define _Included_xin_manong_search_knn_index_faiss_FAISSIndexFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     xin_manong_search_knn_index_faiss_FAISSIndexFactory
 * Method:    build
 * Signature: ([I[[FLjava/lang/String;Ljava/lang/String;Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_xin_manong_search_knn_index_faiss_FAISSIndexFactory_build
  (JNIEnv *, jobject, jintArray, jobjectArray, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
